In [1]:
import contrans
import json
import pprint
import pandas as pd
import pymongo

In [2]:
contrans_obj = contrans.contrans()

In [3]:
bioguides = contrans_obj.get_bioguideIDs()
bioguides

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,N000188,1.0,"Norcross, Donald",Democratic,New Jersey,2024-11-05T20:52:08Z,https://api.congress.gov/v3/member/N000188?for...,Image courtesy of the Member,https://www.congress.gov/img/member/n000188_20...,"[{'chamber': 'House of Representatives', 'star..."
1,Y000064,NaN,"Young, Todd",Republican,Indiana,2024-11-04T13:42:35Z,https://api.congress.gov/v3/member/Y000064?for...,Image courtesy of the Member,https://www.congress.gov/img/member/y000064_20...,"[{'chamber': 'House of Representatives', 'endY..."
2,W000802,NaN,"Whitehouse, Sheldon",Democratic,Rhode Island,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000802?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000802_20...,"[{'chamber': 'Senate', 'startYear': 2007}]"
3,W000800,NaN,"Welch, Peter",Democratic,Vermont,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000800?for...,Image courtesy of the Member,https://www.congress.gov/img/member/w000800_20...,"[{'chamber': 'House of Representatives', 'endY..."
4,W000779,NaN,"Wyden, Ron",Democratic,Oregon,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000779?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000779_20...,"[{'chamber': 'House of Representatives', 'endY..."
...,...,...,...,...,...,...,...,...,...,...
534,C001087,1.0,"Crawford, Eric A. ""Rick""",Republican,Arkansas,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/C001087?for...,Image courtesy of the Member,https://www.congress.gov/img/member/c001087_20...,"[{'chamber': 'House of Representatives', 'star..."
535,S001185,7.0,"Sewell, Terri A.",Democratic,Alabama,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/S001185?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001185_20...,"[{'chamber': 'House of Representatives', 'star..."
536,A000055,4.0,"Aderholt, Robert B.",Republican,Alabama,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/A000055?for...,Image courtesy of the Member,https://www.congress.gov/img/member/a000055_20...,"[{'chamber': 'House of Representatives', 'star..."
537,R000575,3.0,"Rogers, Mike D.",Republican,Alabama,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/R000575?for...,Congressional Pictorial Directory,https://www.congress.gov/img/member/116_rp_al_...,"[{'chamber': 'House of Representatives', 'star..."
538,S001192,2.0,"Stewart, Chris",Republican,Utah,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,"[{'chamber': 'House of Representatives', 'endY..."

In [4]:
bioguides['lastname'] = [x.split(",")[0] for x in bioguides['name']]
bioguides['firstname'] = [x.split(",")[1] for x in bioguides['name']]

replace_map = {"Republican": "R",
               "Democratic": "D",
               "Independent": "I"}
bioguides['partyLetter'] = bioguides['partyName'].replace(replace_map)

bioguides['name2'] = [x + " " + y + " (" + z + ")" for x, y, z in zip(bioguides['firstname'], bioguides['lastname'], bioguides['partyLetter'])]
bioguides['name2']

0               Donald Norcross (D)
1                    Todd Young (R)
2            Sheldon Whitehouse (D)
3                   Peter Welch (D)
4                     Ron Wyden (D)
                   ...
534     Eric A. "Rick" Crawford (R)
535             Terri A. Sewell (D)
536          Robert B. Aderholt (R)
537              Mike D. Rogers (R)
538               Chris Stewart (R)
Name: name2, Length: 539, dtype: object

In [5]:
# import requests
# r = requests.get(l[0]['url'], params = {"api_key": contrans_obj.congress_api_key})
# txt_url = json.loads(r.text)['bill']['textVersions']['url']
# r2 = requests.get(txt_url, params={"api_key": contrans_obj.congress_api_key})
# url_to_scrape = json.loads(r2.text)['textVersions'][0]['formats'][0]['url']

In [6]:
# from bs4 import BeautifulSoup

# html_doc = requests.get(url_to_scrape)
# gumbo = BeautifulSoup(html_doc.text, 'html.parser')
# print(type(gumbo))
# gumbo

In [7]:
# def get_bill_data(bill_url):
#     r = requests.get(bill_url, params = {"api_key": contrans_obj.congress_api_key})
#     txt_url = json.loads(r.text)['bill']['textVersions']['url']
#     r2 = requests.get(txt_url, params={"api_key": contrans_obj.congress_api_key})
#     url_to_scrape = json.loads(r2.text)['textVersions'][0]['formats'][0]['url']

#     html_doc = requests.get(url_to_scrape)
#     gumbo = BeautifulSoup(html_doc.text, 'html.parser') 
#     return gumbo

In [5]:
cands = pd.read_csv("data/cands22.txt", quotechar="|", header=None)
cands.columns = ['Cycle', 'FECCandID', 'CID','FirstLastP',
                 'Party','DistIDRunFor','DistIDCurr',
                 'CurrCand','CycleCand','CRPICO','RecipCode','NoPacs']
cands

,Cycle,FECCandID,CID,FirstLastP,Party,DistIDRunFor,DistIDCurr,CurrCand,CycleCand,CRPICO,RecipCode,NoPacs
0,2022,H0AK00105,N00039029,Thomas Lamb (3),3,AK01,,,,,3N,
1,2022,H0AL01055,N00044245,Jerry Carl (R),R,AL01,AL01,Y,Y,I,RW,
2,2022,H0AL01063,N00044288,Wes Lambert (R),R,AL01,,,,,RN,
3,2022,H0AL01097,N00044750,James Averhart (D),D,AL01,,,,,DN,
4,2022,H0AL02087,N00030768,Martha Roby (R),R,AL02,,,,,RN,
...,...,...,...,...,...,...,...,...,...,...,...,...
8923,2022,S8WI00224,N00041929,Leah Vukmir (R),R,WIS1,,,,,RN,
8924,2022,S8WV00119,N00041293,Paula Jean Swearengin (D),D,WVS2,,,,,DN,
8925,2022,S8WV00127,N00035531,Evan Jenkins (R),R,WVS1,,,,,RN,
8926,2022,S8WV00135,N00041474,Bo Copley (R),R,WVS1,,,,,RN,
8927,2022,S8WV00143,N00012642,Patrick Morrisey (R),R,WVS1,,,,,RN,

In [9]:
# want to join candidates table and the bioguides table
# what are we matching on, what kind of merge do we want? (One to one)
# What rows aren't matched and how to we fix
# crosswalk = pd.merge(bioguides, cands, 
#                      how='left', 
#                      left_on="name2", 
#                      right_on="FirstLastP",
#                      indicator = "matched",
#                      validate = "one_to_one"
#                      )
# crosswalk

In [6]:
members = contrans_obj.make_cand_table()

In [7]:
members['terms.item'][481]

[{'chamber': 'House of Representatives', 'startYear': 1993}]

In [8]:
terms, members = contrans_obj.terms_df(members)

In [9]:
terms

                     chamber  startYear bioguideId  endYear
0   House of Representatives       2014    N000188      NaN
0   House of Representatives       2011    Y000064   2017.0
1                     Senate       2017    Y000064      NaN
0                     Senate       2007    W000802      NaN
0   House of Representatives       2007    W000800   2023.0
..                       ...        ...        ...      ...
0   House of Representatives       2011    C001087      NaN
0   House of Representatives       2011    S001185      NaN
0   House of Representatives       1997    A000055      NaN
0   House of Representatives       2003    R000575      NaN
0   House of Representatives       2013    S001192   2023.0

[594 rows x 4 columns]

In [10]:
members

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,partyletter,DistIDRunFor,lastname,firstname,name2,CID
0,N000188,01,"Norcross, Donald",Democratic,NJ,2024-11-05T20:52:08Z,https://api.congress.gov/v3/member/N000188?for...,Image courtesy of the Member,https://www.congress.gov/img/member/n000188_20...,D,NJ01,Norcross,Donald,Norcross (D),N00036154
1,Y000064,S,"Young, Todd",Republican,IN,2024-11-04T13:42:35Z,https://api.congress.gov/v3/member/Y000064?for...,Image courtesy of the Member,https://www.congress.gov/img/member/y000064_20...,R,INS,Young,Todd,Young (R),N00030670
2,W000802,S,"Whitehouse, Sheldon",Democratic,RI,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000802?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000802_20...,D,RIS,Whitehouse,Sheldon,Whitehouse (D),N00027533
3,W000800,S,"Welch, Peter",Democratic,VT,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000800?for...,Image courtesy of the Member,https://www.congress.gov/img/member/w000800_20...,D,VTS,Welch,Peter,Welch (D),N00000515
4,W000779,S,"Wyden, Ron",Democratic,OR,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000779?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000779_20...,D,ORS,Wyden,Ron,Wyden (D),N00007724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C001087,01,"Crawford, Eric A. ""Rick""",Republican,AR,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/C001087?for...,Image courtesy of the Member,https://www.congress.gov/img/member/c001087_20...,R,AR01,Crawford,"Eric A. ""Rick""",Crawford (R),N00030770
535,S001185,07,"Sewell, Terri A.",Democratic,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/S001185?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001185_20...,D,AL07,Sewell,Terri A.,Sewell (D),N00030622
536,A000055,04,"Aderholt, Robert B.",Republican,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/A000055?for...,Image courtesy of the Member,https://www.congress.gov/img/member/a000055_20...,R,AL04,Aderholt,Robert B.,Aderholt (R),N00003028
537,R000575,03,"Rogers, Mike D.",Republican,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/R000575?for...,Congressional Pictorial Directory,https://www.congress.gov/img/member/116_rp_al_...,R,AL03,Rogers,Mike D.,Rogers (R),N00024759
538,S001192,02,"Stewart, Chris",Republican,UT,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,R,UT02,Stewart,Chris,Stewart (R),N00033932

# Above

The above is now in first normal form.

In [11]:
votes = contrans_obj.get_votes()

In [12]:
pw = contrans_obj.postgres_password
dbserver, engine = contrans_obj.connect_to_postgres(password=pw, create_contrans=True)

In [13]:
members = contrans_obj.get_bioguideIDs()
members = contrans_obj.make_cand_table()
terms, members = contrans_obj.terms_df(members)
ideology = contrans_obj.get_ideology()
contrans_obj.make_members_df(members, ideology, engine)

,bioguideid,district,name,partyname,state,updatedate,url,depiction_attribution,depiction_imageurl,partyletter,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,N000188,01,"Norcross, Donald",Democratic,NJ,2024-11-05T20:52:08Z,https://api.congress.gov/v3/member/N000188?for...,Image courtesy of the Member,https://www.congress.gov/img/member/n000188_20...,D,...,NaN,-0.419,0.340,-50.96336,0.95060,1006.0,23.0,NaN,-0.391,0.370
1,Y000064,S,"Young, Todd",Republican,IN,2024-11-04T13:42:35Z,https://api.congress.gov/v3/member/Y000064?for...,Image courtesy of the Member,https://www.congress.gov/img/member/y000064_20...,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W000802,S,"Whitehouse, Sheldon",Democratic,RI,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000802?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000802_20...,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W000800,S,"Welch, Peter",Democratic,VT,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000800?for...,Image courtesy of the Member,https://www.congress.gov/img/member/w000800_20...,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,W000779,S,"Wyden, Ron",Democratic,OR,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000779?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000779_20...,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,C001087,01,"Crawford, Eric A. ""Rick""",Republican,AR,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/C001087?for...,Image courtesy of the Member,https://www.congress.gov/img/member/c001087_20...,R,...,NaN,0.460,0.307,-161.93731,0.85720,1051.0,66.0,NaN,0.466,0.174
535,S001185,07,"Sewell, Terri A.",Democratic,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/S001185?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001185_20...,D,...,NaN,-0.402,0.396,-51.44477,0.94995,1002.0,18.0,NaN,-0.524,0.368
536,A000055,04,"Aderholt, Robert B.",Republican,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/A000055?for...,Image courtesy of the Member,https://www.congress.gov/img/member/a000055_20...,R,...,NaN,0.405,0.467,-173.56776,0.84683,1044.0,85.0,NaN,0.464,0.271
537,R000575,03,"Rogers, Mike D.",Republican,AL,2024-06-08T18:40:14Z,https://api.congress.gov/v3/member/R000575?for...,Congressional Pictorial Directory,https://www.congress.gov/img/member/116_rp_al_...,R,...,NaN,0.379,0.376,-161.36951,0.85666,1043.0,79.0,NaN,0.449,0.348
538,S001192,02,"Stewart, Chris",Republican,UT,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,R,...,NaN,0.499,0.167,-20.09721,0.94194,336.0,9.0,NaN,0.437,0.141

In [14]:
contrans_obj.make_terms_df(terms, engine)
contrans_obj.make_votes_df(votes, engine)

In [15]:
myquery = '''
SELECT *
    FROM (
        SELECT 
            chamber, 
            rollnumber, 
            icpsr as icpsr_1,
            cast_code as vote_1,
            FROM votes
        WHERE icpsr=14854
    )
'''
pd.read_sql_query(myquery, con=engine)

ProgrammingError: (psycopg.errors.SyntaxError) syntax error at or near "FROM"
LINE 9:             FROM votes
                    ^
[SQL:
SELECT *
    FROM (
        SELECT
            chamber,
            rollnumber,
            icpsr as icpsr_1,
            cast_code as vote_1,
            FROM votes
        WHERE icpsr=14854
    )
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [16]:
myquery = '''
SELECT 
    name AS congressperson,
    partyname AS party,
    state AS us_state,
    district AS congressional_district
FROM members
WHERE partyname='Democratic'
'''
pd.read_sql_query(myquery, con=engine)

            congressperson       party us_state congressional_district
0         Norcross, Donald  Democratic       NJ                     01
1      Whitehouse, Sheldon  Democratic       RI                      S
2             Welch, Peter  Democratic       VT                      S
3               Wyden, Ron  Democratic       OR                      S
4      Warnock, Raphael G.  Democratic       GA                      S
..                     ...         ...      ...                    ...
257      Sánchez, Linda T.  Democratic       CA                     38
258        Schiff, Adam B.  Democratic       CA                     30
259         Eshoo, Anna G.  Democratic       CA                     16
260  Peltola, Mary Sattler  Democratic       AK                      S
261       Sewell, Terri A.  Democratic       AL                     07

[262 rows x 4 columns]

In [ ]:
new_query = """
SELECT 
    a.icpsr as icpsr_1,
    b.icpsr as icpsr_2,
    AVG(CASE WHEN a.cast_code = b.cast_code THEN 1 ELSE 0 END) as agree
    FROM votes AS a
INNER JOIN votes AS b
    ON a.chamber=b.chamber 
    AND a.rollnumber=b.rollnumber 
WHERE a.icpsr=14854 and a.icpsr!=b.icpsr
GROUP BY icpsr_1, icpsr_2
ORDER BY agree DESC
"""
pd.read_sql(new_query, con=engine)

     icpsr_1  icpsr_2     agree
0      14854    21108  0.932651
1      14854    22378  0.927928
2      14854    29323  0.922421
3      14854    22124  0.913043
4      14854    22336  0.905371
..       ...      ...       ...
443    14854    21566  0.271952
444    14854    21172  0.246914
445    14854    29573  0.230196
446    14854    22106  0.217391
447    14854    20305  0.214834

[448 rows x 3 columns]

In [ ]:
my_query = """ 
SELECT m.name, m.partyname, m.state, m.district, CAST(m.icpsr AS INT) as icpsr, v.agree
    FROM members as m
INNER JOIN (
            SELECT 
                a.icpsr as icpsr_1,
                b.icpsr as icpsr_2,
                AVG(CASE WHEN a.cast_code = b.cast_code THEN 1 ELSE 0 END) as agree
                FROM votes AS a
            INNER JOIN votes AS b
                ON a.chamber=b.chamber 
                AND a.rollnumber=b.rollnumber 
            WHERE a.icpsr=14854 and a.icpsr!=b.icpsr
            GROUP BY icpsr_1, icpsr_2
            ORDER BY agree DESC
) as v
    on CAST(m.icpsr AS INT) = v.icpsr_2
WHERE icpsr IS NOT NULL
ORDER BY v.agree
"""
pd.read_sql(my_query, con=engine)

,name,partyname,state,district,icpsr,agree
0,"Grijalva, Raúl M.",Democratic,AZ,07,20305,0.214834
1,"Bush, Cori",Democratic,MO,01,22106,0.217391
2,"Evans, Dwight",Democratic,PA,03,21566,0.271952
3,"Bowman, Jamaal",Democratic,NY,16,22105,0.286445
4,"Sablan, Gregorio Kilili Camacho",Democratic,MP,S,21996,0.298507
...,...,...,...,...,...,...
433,"Kiley, Kevin",Republican,CA,03,22336,0.905371
434,"Hinson, Ashley",Republican,IA,02,22124,0.913043
435,"Calvert, Ken",Republican,CA,41,29323,0.922421
436,"Fong, Vince",Republican,CA,20,22378,0.927928
437,"Womack, Steve",Republican,AR,03,21108,0.932651

In [30]:
import os
mongo_user = os.getenv("MONGO_INITDB_ROOT_USERNAME")
mongo_pw = os.getenv("MONGO_INITDB_ROOT_PASSWORD")

myclient = pymongo.MongoClient(f"mongodb://{mongo_user}:{mongo_pw}@localhost:27017/")

In [ ]:

# create a database 
mongo_contrans = myclient['contrans']

# create a collection in the database where the records will go
mongo_bills = mongo_contrans['bills']

In [25]:
pd.read_sql_query(myquery, con=engine)
bioguideids = contrans_obj.get_bioguideIDs()['bioguideId']
bill_list = contrans_obj.get_sponsored_legislation(bioguideids[0])
onebill = contrans_obj.get_bill_data(bill_list[0]['url'])
len(bill_list)

88

In [ ]:
myclient.insert_one(onebill)