In [2]:
import contrans
import json
import pprint
import pandas as pd
import pymongo
import os
from plotly import express as px

In [3]:
contrans_obj = contrans.contrans()

In [4]:
server, engine = contrans_obj.connect_to_postgres(password=os.getenv("POSTGRES_PASSWORD"))

In [5]:
# 
myquery = """
SELECT *
FROM members
"""
members = pd.read_sql_query(myquery, con=engine)
members
# members['firstname'] + " " + members['lastname'] + " (" + members['partyletter'] + ", " + members['state'] + "-" + members['district'] + ")"

,bioguideid,district,name,partyname,state,updatedate,url,depiction_attribution,depiction_imageurl,partyletter,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,N000188,01,"Norcross, Donald",Democratic,NJ,2024-11-05T20:52:08Z,https://api.congress.gov/v3/member/N000188?for...,Image courtesy of the Member,https://www.congress.gov/img/member/n000188_20...,D,...,None,-0.419,0.340,-50.96336,0.95060,1006.0,23.0,None,-0.391,0.370
1,Y000064,S,"Young, Todd",Republican,IN,2024-11-04T13:42:35Z,https://api.congress.gov/v3/member/Y000064?for...,Image courtesy of the Member,https://www.congress.gov/img/member/y000064_20...,R,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
2,W000802,S,"Whitehouse, Sheldon",Democratic,RI,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000802?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000802_20...,D,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
3,W000800,S,"Welch, Peter",Democratic,VT,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000800?for...,Image courtesy of the Member,https://www.congress.gov/img/member/w000800_20...,D,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
4,W000779,S,"Wyden, Ron",Democratic,OR,2024-11-04T13:42:34Z,https://api.congress.gov/v3/member/W000779?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/w000779_20...,D,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,H001038,26,"Higgins, Brian",Democratic,NY,2024-05-07T18:43:22Z,https://api.congress.gov/v3/member/H001038?for...,"Image, Congressional Pictorial Directory, 109th.",https://www.congress.gov/img/member/h001038_20...,D,...,None,-0.348,-0.032,-37.78669,0.94548,674.0,17.0,None,-0.333,-0.035
548,S001222,03,"Santos, George",Republican,NY,2024-03-04T13:52:36Z,https://api.congress.gov/v3/member/S001222?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001222_20...,R,...,None,0.473,-0.421,-117.88222,0.81608,580.0,47.0,None,0.473,-0.420
549,S001192,02,"Stewart, Chris",Republican,UT,2024-02-26T19:36:16Z,https://api.congress.gov/v3/member/S001192?for...,Image courtesy of the Member,https://www.congress.gov/img/member/s001192_20...,R,...,None,0.499,0.167,-20.09721,0.94194,336.0,9.0,None,0.437,0.141
550,F000062,S,"Feinstein, Dianne",Democratic,CA,2023-10-19T16:13:13Z,https://api.congress.gov/v3/member/F000062?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/f000062_20...,D,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
551,S001197,S,"Sasse, Ben",Republican,NE,2023-01-26T16:10:43Z,https://api.congress.gov/v3/member/S001197?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/s001197_20...,R,...,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN

In [1]:
def plot_ideology(self, bioguide_id):
                member_ideo = ideo.query(f"bioguideid == {bioguide_id}").reset_index(drop=True)
                fig = px.histogram(ideo, x='nominate_dim1',
                                nbins=60,
                                title='Distribution of Nominate Dim1',
                                color='partyname')
                fig.update_xaxes(title_text="Left-Right Ideology")
                fig.update_layout(title_x=0.5)
                fig.update_layout(title_text="How Liberal or Conservative Is this Person?", title_x=0.5)
                fig.update_layout(legend_title_text='Party')
                fig.update_xaxes(tickvals=[-.5, 0, .5], ticktext=["Liberal", "Centrist", "Conservative"])
                fig.add_vline(x=0, line_width=1, line_color="black")
                fig.add_vline(x=member_ideo.iloc[0]['nominate_dim1'], line_width=3, line_dash="dash", line_color="red")
                fig.update_layout(hovermode="closest")
                fig.add_annotation(text=f"{member_ideo.iloc[0]['name']} ({member_ideo.iloc[0]['state']}-{member_ideo.iloc[0]['district']})",
                                xref="x", yref="paper",
                                x=member_ideo.iloc[0]['nominate_dim1'], y=1.05,
                                showarrow=False,
                                font=dict(size=12, color="red"))
                return fig

In [7]:
bills_mongo = contrans_obj.connect_to_mongo() # from_scratch will replace all other work and you will have to reupload things

In [ ]:
all_congresspeople = list(bioguides['bioguideId'])
contrans_obj.upload_many_members_to_mongo(mongo_bills=bills_mongo, members=all_congresspeople)

In [9]:
contrans_obj.query_mongo(bills_mongo, {}, {})

,_id,bill,request,bill_text
0,673237bd8af88af903e0479c,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '9983', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
1,673237bd8af88af903e0479d,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '1515', 'billType': 'hres', 'co...",\n[Congressional Bills 118th Congress]\n[From ...
2,673237bd8af88af903e0479e,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '9635', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
3,673237bd8af88af903e0479f,"{'actions': {'count': 4, 'url': 'https://api.c...","{'billNumber': '9419', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
4,673237bd8af88af903e047a0,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '8639', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
...,...,...,...,...
276,673238f38af88af903e048b0,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1272', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
277,673238f38af88af903e048b1,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '700', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
278,673238f38af88af903e048b2,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '482', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
279,673238f38af88af903e048b3,"{'actions': {'count': 4, 'url': 'https://api.c...","{'billNumber': '50', 'billType': 'sres', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
280,673238f38af88af903e048b4,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3140', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...

In [10]:
contrans_obj.query_mongo_search_engine(bills_mongo, "bill_text", "historical ships")

,_id,bill,request,bill_text
0,6732389a8af88af903e04829,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '5114', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
1,673237e28af88af903e047b0,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '9983', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
2,673237bd8af88af903e0479c,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '9983', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
3,673237e28af88af903e047bb,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '5334', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
4,673237bd8af88af903e047a7,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '5334', 'billType': 'hr', 'cong...",\n[Congressional Bills 118th Congress]\n[From ...
5,673238088af88af903e047d8,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3675', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
6,673238088af88af903e047c8,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1688', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
7,6732384a8af88af903e047fb,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4338', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
8,673238f38af88af903e04889,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3234', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
9,673238f38af88af903e0488f,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3310', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
10,6732389a8af88af903e04833,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4742', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
11,673238f38af88af903e04896,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '2892', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
12,6732389a8af88af903e04840,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '649', 'billType': 'sres', 'con...",\n[Congressional Bills 118th Congress]\n[From ...
13,6732384a8af88af903e0481f,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '440', 'billType': 'sres', 'con...",\n[Congressional Bills 118th Congress]\n[From ...
14,6732384a8af88af903e047e9,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '871', 'billType': 'sres', 'con...",\n[Congressional Bills 118th Congress]\n[From ...
15,673238f38af88af903e048a8,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1668', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
16,673238088af88af903e047dc,"{'actions': {'count': 6, 'url': 'https://api.c...","{'billNumber': '26', 'billType': 'sconres', 'c...",\n[Congressional Bills 118th Congress]\n[From ...
17,673238088af88af903e047c9,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4413', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
18,673238f38af88af903e04897,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '350', 'billType': 'sres', 'con...",\n[Congressional Bills 118th Congress]\n[From ...
19,673238f38af88af903e04870,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '822', 'billType': 'sres', 'con...",\n[Congressional Bills 118th Congress]\n[From ...
20,673238f38af88af903e048ac,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3692', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
21,6732389a8af88af903e04842,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4154', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
22,6732389a8af88af903e04843,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4084', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
23,673238f38af88af903e048b1,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '700', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
24,6732389a8af88af903e04859,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1936', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
25,673238f38af88af903e048a9,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3893', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
26,673238f38af88af903e0488b,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3517', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
27,6732384a8af88af903e0481b,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '946', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
28,6732389a8af88af903e04850,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '2557', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
29,6732384a8af88af903e047fa,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '512', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
30,673238f38af88af903e0488a,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '3436', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
31,673238f38af88af903e0486e,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '5243', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
32,673238f38af88af903e0486c,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '5236', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
33,673238f38af88af903e0488c,"{'actions': {'count': 4, 'url': 'https://api.c...","{'billNumber': '3430', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
34,673238088af88af903e047e1,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '136', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
35,6732384a8af88af903e04803,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1531', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
36,673238f38af88af903e048aa,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '680', 'billType': 's', 'congre...",\n[Congressional Bills 118th Congress]\n[From ...
37,6732384a8af88af903e0480e,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '1920', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
38,673237e28af88af903e047c3,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '299', 'billType': 'hr', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
39,673237bd8af88af903e047af,"{'actions': {'count': 3, 'url': 'https://api.c...","{'billNumber': '299', 'billType': 'hr', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
40,673238f38af88af903e04892,"{'actions': {'count': 5, 'url': 'https://api.c...","{'billNumber': '3084', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
41,673238088af88af903e047cd,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '4141', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
42,6732389a8af88af903e0482b,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '5021', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...
43,6732389a8af88af903e04851,"{'actions': {'count': 2, 'url': 'https://api.c...","{'billNumber': '2670', 'billType': 's', 'congr...",\n[Congressional Bills 118th Congress]\n[From ...